CREATE DATABASE IF NOT EXISTS STUDENTS CHARACTER SET=utf8 COLLATE utf8_general_ci;

USE STUDENTS;
CREATE TABLE SGroup (
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	PRIMARY KEY(ID)
);


CREATE TABLE STUDENT(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
	BIRTHDAY VARCHAR(255),
    SGROUP_ID INT,
	PRIMARY KEY(ID),
	FOREIGN KEY (SGROUP_ID)
	REFERENCES `SGroup`(ID) ON DELETE SET NULL
);